### ISSUE TITLE
500 errors

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/VIM#167]
<img width="694" alt="image" src="https://github.com/user-attachments/assets/93536ab4-f856-496e-8bbe-f9fe1c9522f9">
I'm getting a 500 error when I try to go to "Instruments" on UMIL...

**Comment by kunfang98927** [comment]
I'll look into and fix this.

**Comment by kunfang98927** [comment]
I found the reason of this issue. We were using lowercases in urls, e.g., "https://vim.simssa.ca/instruments/?language=french"
But after we updated the language list, the `en_label` for each language are uppercases. I'll fix it to keep the case consistent.

**Comment by fujinaga** [comment]
This is not fixed for many languages, including Japanese: [https://vim.simssa.ca/instruments/?language=Japanese](url).

**Comment by notkaramel** [comment]
I asked to access the production server to trace the error there. I couldn't replicate the 500 error locally.

For example: I want to get the instrument page in Korean

| - | `localhost` Development | Production | 
| ------ | ----------- | ---------- |
| `GET /instruments/?language=Korean` | ![][1] <br> Note that all labels are missing here, but the page loads fine | ![][2] |
| Server Response Code | 200 OK | 500 Internal Server Error |
| Docker log | ![][3] | Need to find out|

My suspicion about "the webapp unable to retrieve from the database causes the error" might not hold true on this, it was my fault for not reading the README (*very rookie mistake*) to run the `load_instruments` scripts

[1]: https://github.com/user-attachments/assets/db154156-2242-41ce-ae17-f963dcc45bb2
[2]: https://github.com/user-attachments/assets/7866d9b0-70ca-445c-afc0-6c5bdfd909c1
[3]: https://github.com/user-attachments/assets/9c568b56-b896-4b64-9ecb-9fa5537d6e41

**Comment by notkaramel** [comment]
I tracked this down in VIM/UMIL production server and found that it is an NGINX issue.

Sending an HTTP request with different langauge than English or French returns `500` immediately, which can be seen with 
```sh
docker logs vim-nginx -f --tail 5
```

![Image](https://github.com/user-attachments/assets/697555ab-a95b-456a-9cb1-03f1a48ff0e5)

No logs appears on `vim-app` or `vim-db`, so there's no issue from that end I believe. I will investigate more on how to resolve this issue

> Sidenote: While I was tracing this bug, there's a logic error on `vim-app`. I suspect it's unrelated to this, I will take a look on it another time.

**Comment by dchiller** [comment]
I wouldn't necessarily interpret it that way... since nginx is just proxying this request to the django app, it would be odd to me if whether or not it errored changed with a query parameter.  Since the django app is running in production mode, unless there is specific logging set up for this I wouldn't necessarily expect an error in the django logs. 

Does this happen locally? If it does, then I suspect this issue is already solved...it doesn't happen in the branch being reviewed here: https://github.com/DDMAL/VIM/pull/164.

**Comment by notkaramel** [comment]
I'm also referring to this website about *nginx 500 internal server error*
https://www.netdata.cloud/academy/how-to-fix-nginx-500-internal-server-error-simple-steps-for-troubleshooting/

**Comment by dchiller** [comment]
Also, did you check the logs for the solr container? Are they erroring?

**Comment by notkaramel** [comment]
No, they are not!

`solr` only logs when it's `/?language=English` or `/?language=French`. I'm thinking that the request with different languages couldn't reach django app or solr...

**Comment by notkaramel** [comment]
I enabled `--log-level debug` in staging `web-app/django-startup.sh`
```diff
- gunicorn -w 2 -b 0:8001 VIM.wsgi
+ gunicorn -w 2 -b 0:8001 VIM.wsgi --log-level debug
```

Sending requests to both `/instruments/?language=English` and `/instruments/?language=Japanese` gives the same debug log with no error appearing
```
[2025-05-09 17:44:03 +0000] [10] [DEBUG] GET /instruments/
[2025-05-09 17:44:05 +0000] [11] [DEBUG] GET /instruments/
[2025-05-09 17:44:06 +0000] [10] [DEBUG] GET /instruments/
[2025-05-09 17:44:07 +0000] [11] [DEBUG] GET /instruments/
[2025-05-09 17:44:09 +0000] [10] [DEBUG] GET /instruments/
```

**Comment by notkaramel** [comment]
I also did the same thing for Solr debug and compare the debug logs for `?language=English` and `?language=Japanese`. The request went through without any error, so I don't think `solr` is the issue.

```yml
  environment:
    - SOLR_LOG_LEVEL=DEBUG
```

Note: Solr error is expected to look like a Java Runtime Error, i.e., have a clear traceback of function calls. ChatGPT gave this example error message below, which the Solr logs were clear of it.
```
[...] DEBUG (...) [   x:gettingstarted] o.a.s.c.SolrCore [gettingstarted] org.apache.solr.common.SolrException: org.apache.lucene.queryparser.classic.ParseException: Cannot parse '+title:': Encountered "<EOF>" at line 1, column 7.
Was expecting one of:
    ...
    at org.apache.solr.search.SolrIndexSearcher.search(SolrIndexSearcher.java:987)
    at org.apache.solr.handler.component.QueryComponent.process(QueryComponent.java:517)
    at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:309)
    at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:199)
Caused by: org.apache.lucene.queryparser.classic.ParseException: Cannot parse '+title:': Encountered "<EOF>" at line 1, column 7.
...
```

**Comment by ahankinson** [comment]
This is pretty easy to replicate if you're running it locally. I got the Django app up and running and get this traceback:

![Image](https://github.com/user-attachments/assets/84c64542-1c97-4efd-8124-dabfdfcea02f)

This is because of the call to Solr, specifically the facet query:

`f"facet.pivot=hbs_prim_cat_s,hbs_prim_cat_label_{active_language_code}_s"`

So when I'm asking for German, for example, it's asking for `hbs_prim_cat_label_de_s`, but this field doesn't exist in Solr. This makes the code fail on line 71 when you're assuming that the response contains this field:

**Comment by notkaramel** [comment]
Wow thanks @ahankinson!

It didn't happen to me on my local development, [I mentioned it](https://github.com/DDMAL/VIM/issues/167#issuecomment-2674943650) few comments before (it was on a Windows machine). I tried it again (this time on Linux) and it still works fine without any errors for me.

![Image](https://github.com/user-attachments/assets/1e63aecb-87d1-4ce9-98ce-0b40411dbcf2)

I'm guessing this might have to do with Solr running on different OS?

**Comment by ahankinson** [comment]
The underlying error is that you're looking up a key in a dictionary that doesn't exist, so that is the same on all OSes. 

Either the code you are running is different, or the data in Solr is different, for you to get that result. You should check for the presence of a field called `hbs_prim_cat_label_de_s` in Solr. If it's not there, then you should step through the code.

**Comment by notkaramel** [comment]
Thank you @ahankinson!

I have an unexpected discovery yesterday: On staging server, I prune all Docker images and rebuilt UMIL, the 500 errors _magically_ disappear, similar behaviour as when developing locally. The catch is that now the Hornbostel-Sachs Classification is gone. You can see it here: https://umil.staging.linkedmusic.ca/instruments/

![Image](https://github.com/user-attachments/assets/26155dee-f00a-4ea0-9d0e-c4cbaf217046)

I also found the part of the code that interact with Solr as you mentioned:
https://github.com/DDMAL/VIM/blob/a15a3e8b512adeee6c7b9f62817a6ad0afe73a74/web-app/django/VIM/apps/instruments/views/instrument_list.py#L59

I've not done anything on production UMIL so far, but it's up-to-date with `develop` branch.

**Comment by notkaramel** [comment]
Well I think I can open a new issue relating to this, now that we know Solr is the cause of the 500 error code.

Production on 502 rn is because the server is down, sadly. Will get it back up ASAP
